addBlockRequest message modified
noted-eip/protorepo pull request #8
Opened 2022-05-27 10:13 UTC by gabriel654165

added a string id field in addBlockRequest in order to specify a note to add a block into

2022-05-27 10:17 UTC, rojas-diego requested changes

2022-05-27 10:17 UTC, rojas-diego commented on notes/notes.proto
> +    string id = 1;
```suggestion
    string note_id = 1;
```

2022-05-27 10:18 UTC, gabriel654165 commented on notes/notes.proto
> +    string id = 1;
Yes right !

2022-05-27 18:29 UTC, rojas-diego commented on notes/notes.proto
> +    string note_id = 1;
Mhm, do we really need this? a `Block.id` is supposed to be unique across all notes right (aka `Block.id` is sufficient to uniquely identify a block)? Only reason why we might need it is to simplify the authorisation process.

2022-05-27 18:31 UTC, rojas-diego commented on notes/notes.proto
> +    string note_id = 1;
I don't get it, how do you know which block to update if you only pass in a `note_id`. I think we should keep the `id` as it was.

2022-06-22 20:46 UTC, rojas-diego commented
Any updates on this?

2022-06-27 18:08 UTC, rojas-diego commented
__Please ignore this message__ #17

2022-07-09 13:07 UTC, closed without merging